skip_tags: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -Ur test-requirements.txt"
  - "pip install codecov"

test_script:
  # This is pretty lazy -- we don't go into an empty dir or anything.
  # I think pytest will test the installed version? But I dunno the
  # coverage will actually work right if just given as "trustme"
  - python -u -m pytest
  - "codecov -F windows"

on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\.test-results\pytest\results.xml))

branches:
  except:
    - /dependabot/.*/
